apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: consoles.app.coreos.com
spec:
  group: app.coreos.com
  version: v1alpha1
  scope: Namespaced
  names:
    plural: consoles
    singular: console
    kind: Console
    listKind: ConsoleList
    shortNames:
      - co
  validation:
    openAPIV3Schema:
      type: object
      description: Represents and describes the current state of a console application
      required:
      - spec
      properties:
        spec:
          type: object
          description: Spec for a Console
          required:
          - size
          properties:
            size:
              type: integer
              description: Number of pods in the deployment
