apiVersion: app.coreos.com/v1alpha1
kind: ClusterServiceVersion-v1
metadata:
  name: console-operator.v0.0.1
  annotations:
    alm-examples: '[{"apiVersion":"app.coreos.com/v1alpha1","kind":"Console","metadata":{"name":"tectonic-console"},"spec":{"size":2}}]'
spec:
  customresourcedefinitions:
    owned:
      - description: Represents a cluster of Console instances
        displayName: Console
        kind: Console
        name: consoles.app.coreos.com
        resources:
          - kind: Deployment
            name: ''
            version: v1
          - kind: ReplicaSet
            name: ''
            version: v1
          - kind: Pod
            name: ''
            version: v1
          - kind: Service
            name: ''
            version: v1
        specDescriptors:
          - description: The desired number of member Pods for the deployment.
            displayName: Size
            path: size
            x-descriptors:
              - 'urn:alm:descriptor:com.tectonic.ui:podCount'
        statusDescriptors:
          - description: The current status of the application.
            displayName: Status
            path: phase
            x-descriptors:
              - 'urn:alm:descriptor:io.kubernetes.phase'
          - description: Explanation for the current status of the application.
            displayName: Status Details
            path: reason
            x-descriptors:
              - 'urn:alm:descriptor:io.kubernetes.phase:reason'
        version: v1alpha1
  keywords:
    - console
    - app
  displayName: Console
  provider:
    name: 'CoreOS, Inc'
    url: www.coreos.com
  maturity: alpha
  version: 0.0.1
  install:
    spec:
      deployments:
        - name: console-operator
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: console-operator
            template:
              metadata:
                labels:
                  app: console-operator
              spec:
                containers:
                  - image: 'quay.io/alecmerdler/console-operator:latest'
                    imagePullPolicy: Always
                    name: console-operator
                restartPolicy: Always
                serviceAccount: console-operator
                serviceAccountName: console-operator
                terminationGracePeriodSeconds: 5
      permissions:
        - rules:
            - apiGroups:
                - app.coreos.com
              resources:
                - consoles
              verbs:
                - '*'
            - apiGroups:
                - ''
              resources:
                - pods
                - events
                - namespaces
                - services
              verbs:
                - '*'
            - apiGroups:
                - ''
              resources:
                - namespaces
              verbs:
                - get
            - apiGroups:
                - apps
                - extensions
              resources:
                - deployments
              verbs:
                - '*'
          serviceAccountName: console-operator
    strategy: deployment
  maintainers:
    - email: support@coreos.com
      name: 'CoreOS, Inc'
  description: Enterprise Kubernetes dashboard for cluster administrators
  labels:
    alm-owner-enterprise-app: console-operator
    alm-status-descriptors: console-operator.v0.0.1
